

camunda.bpm.admin-user:
  id: demo
  password: demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8000
camunda:
  bpm:
    auto-deployment-enabled: false
    database:
      type: mysql
